sonar.projectKey=sergiobsilva2505_taskmanager-web
sonar.organization=sergiobsilva2505

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/environment*.ts,**/main.ts

sonar.javascript.lcov.reportPaths=coverage/taskmanager-web/lcov.info
sonar.sourceEncoding=UTF-8
